services:
  postgres:
    image: postgres:17-alpine
    container_name: twin-bot-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - bot
    ports:
      - ${DB_PORT}:${DB_PORT}

networks:
  bot:
    driver: bridge
